name: Get & cache deps
description: Get the deps and cache them
inputs:
  caching: 
     description: Whether to cache deps
     required: true
     default: 'true'
outputs: 
  used-cached: 
     description: Whether cach was used-cached
     value: ${{ steps.install.outputs.cache }}
runs: 
  using: composite
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: custom/node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
        echo "cache=${{ inputs.caching }}" >> $GITHUB_ENV
      shell: bash
      working-directory: custom